trigger: none
pr: none

resources:
  pipelines:
    - pipeline: buildPipeline
      source: Resume_ATS_Tracker
      trigger:
        branches:
          - main

variables:
  resourceGroup: 'ats-resume-scanner-rg'
  appServiceName: 'ats-resume-tracker'
  azureSubscription: 'Resume-ATS-Tracker-sc'
pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: DownloadPipelineArtifact@2
    displayName: 'Download build artifact from CI pipeline'
    inputs:
      buildType: 'latest'
      project: '$(System.TeamProject)'
      pipeline: '$(resources.pipeline.buildPipeline.pipelineId)'
      artifact: 'ats-resume-tracker'
      path: '$(Build.ArtifactStagingDirectory)'

  - task: AzureWebApp@1
    displayName: 'Deploy to Azure Web App'
    inputs:
      azureSubscription: '$(azureSubscription)'
      appType: 'webAppLinux'
      appName: '$(appServiceName)'
      package: '$(Build.ArtifactStagingDirectory)/ats-resume-tracker.zip'
      resourceGroupName: '$(resourceGroup)'