trigger: none
pr: none

resources:
  pipelines:
    - pipeline: buildPipeline
      source: SHIVAM-DCE.Resume_ATS_Tracker
      trigger:
        branches:
          - main

variables:
  resourceGroup: 'ats-resume-scanner-rg'
  appServiceName: 'ats-resume-tracker'
  azureSubscription: 'Resume-ATS-Tracker-sc'
pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UniversalPackages@0
    displayName: 'Download Universal Package from Azure Artifacts feed'
    inputs:
      command: 'download'
      downloadDirectory: '$(Build.ArtifactStagingDirectory)'
      feedsToUse: 'select'
      vstsFeed: 'ats-resume-tracker'
      vstsFeedPackage: 'ats-resume-tracker'
      vstsPackageVersion: '1.0.*'

  - task: AzureWebApp@1
    displayName: 'Deploy to Azure Web App'
    inputs:
      azureSubscription: '$(azureSubscription)'
      appType: 'webAppLinux'
      appName: '$(appServiceName)'
      package: '$(Build.ArtifactStagingDirectory)/ats-resume-tracker.zip'
      resourceGroupName: '$(resourceGroup)'
