trigger: none
pr: none

resources:
  pipelines:
    - pipeline: buildPipeline
      source: SHIVAM-DCE.Resume_ATS_Tracker  # Use the actual name of your CI pipeline
      trigger:
        branches:
          include:
            - main

variables:
  resourceGroup: 'ats-resume-scanner-rg'
  slotName: '' # No slot, deploying to production
  appServiceName: 'ats-resume-tracker'
  azureSubscription: 'Resume-ATS-Tracker-sc'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: 'latest'
      project: '$(System.TeamProject)'
      pipeline: '$(resources.pipeline.buildPipeline.pipelineId)'
      artifact: 'ats-resume-tracker'
      path: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Download build artifact from CI pipeline'

  - task: AzureCLI@2
    displayName: 'Check if slot exists'
    inputs:
      azureSubscription: '$(azureSubscription)'
      scriptType: 'ps'
      scriptLocation: 'inlineScript'
      inlineScript: |
        $slot = az webapp deployment slot list --resource-group "$(resourceGroup)" --name "$(appServiceName)" | ConvertFrom-Json | Where-Object { $_.name -eq "$(slotName)" }
        if ($slot) {
          Write-Host "##vso[task.setvariable variable=deployToSlot]true"
        } else {
          Write-Host "##vso[task.setvariable variable=deployToSlot]false"
        }

  - task: AzureWebApp@1
    displayName: 'Deploy to Azure Web App'
    inputs:
      azureSubscription: '$(azureSubscription)'
      appType: 'webApp'
      appName: '$(appServiceName)'
      package: '$(Build.ArtifactStagingDirectory)/ats-resume-tracker.zip'
      resourceGroupName: '$(resourceGroup)'
      deployToSlotOrASE: '$(deployToSlot)'
      slotName: '$(slotName)'
